#! /bin/sh

if [ -x $HOME/.config/bspwm/bspwmLaptopDualMonitor.sh ]; then
    bash $HOME/.config/bspwm/bspwmLaptopDualMonitor.sh 
fi

sxhkd &
setxkbmap us -option caps:swapescape &
./.config/polybar/launch.sh &
picom &
optimus-manager-qt &
nm-applet &
blueman-applet &
flameshot &
nitrogen --restore &

bspc config border_width          2
bspc config window_gap            0

bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           0
